site_name: Docs do Felipe
site_url: https://felipeantoniak.github.io
site_author: Felipe Antoniak

# Configuração do Tema
theme:
  name: material
  language: pt-BR
  palette: 
    - scheme: slate
      primary: teal
      accent: lime
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

# Extensões
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Navegação Corrigida
nav:
  - Home: index.md
  - Estudos:
      - Hack The Box: htb/index.md
      - Redes:
          - Introdução: redes/index.md      # O arquivo index fica aqui dentro
          - Subnetting: redes/subnetting.md # E os outros arquivos logo abaixo
          - Modelo OSI: redes/modelo-osi.md
          - Topologias: redes/topologias.md
      - Linux: linux/index.md
