site_name: Docs do Felipe
site_url: https://felipeantoniak.github.io
site_author: Felipe Antoniak

# Configuração do Tema (Visual Profissional)
theme:
  name: material
  language: pt-BR
  palette: 
    # Modo Escuro (Slate)
    - scheme: slate
      primary: teal
      accent: lime
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

# Extensões (Para deixar o Markdown poderoso)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Navegação (Aqui você organiza suas pastas)
nav:
  - Home: index.md
  - Estudos:
    - Hack The Box: htb/index.md
    - Redes: redes/index.md
        - Introdução: redes/index.md
        - Subnetting: redes/subnetting.md
    - Linux: linux/index.md
